### ISSUE TITLE
Very cool!

### ISSUE THREAD

**Issue by MegaChriz** [silverweed/boomlevelgen#1]
Very cool that a level generator for BOOM exists. :)

A suggestion for improvement could be to put the player in a safe spot by default. Right now (using the default options) in many of the generated levels the player gets immediately attacked at the start of a level.
Another possible improvement would be to be aware of the special level 80. I got six "final" bosses trying to move but they get blocked and where placed on top of non-explodable boxes. Two or three final bosses would be nice though, as long they are not placed on top of boxes.

Thanks for sharing this!

**Comment by silverweed** [comment]
Thank you for the feedback! It's been quite a bit since I last worked on this, but I'm definitely going through your suggestions :-)
The lvl 80 fix should be very easy, while the safe-spot check may be a tiny bit more work, but it's far from impossible, so I hope to release both updates in a reasonable time ;)
(Nice to see someone else who knows this game :D)

**Comment by MegaChriz** [comment]
I know the game since about 15 years ago. I even wrote my own level editor for the classic Mac OS back in the days, in HyperCard. Recently I rediscovered the game after nearly nine years. Initially I was looking for custom level packs. Do you perhaps know a site where BOOM levels are or can be shared? (There is one for the classic PC version of Prince of Persia.)

Appreciate you are considering implementing the improvements! :) Take your time with doing them, I'm happy to wait for it.

**Comment by silverweed** [comment]
Unfortunately I never found such a site...which is bad, since during my years of playing BOOM I'd created a good deal of level sets, and I'd love to share them and try ones made by others. I guess the game is not popular enough to have a critical-mass fanbase - maybe due to the fact it's MacOS-only. Anyway, it's a good idea: who knows, maybe one day if I feel like it I may create my own sharing site :D

**Comment by silverweed** [comment]
Commits https://github.com/silverweed/boomlevelgen/commit/9e3ae2dcfb860a6a09f5847cfb5637d469352ece and https://github.com/silverweed/boomlevelgen/commit/ff099f0173c19c3d6e36f7a5c9f68a237337095d implement basic safety checks for players. It's nothing fancy, but should do the work.
